### ISSUE TITLE
PHP Fatal error:  Uncaught ValueError: Path cannot be empty in [no active file]

### ISSUE THREAD

**Issue by biladina** [yii2-extensions/app-basic#34]
### What steps will reproduce the problem?
- create project with composer
- run `php yii serve`

### What is the expected result?
the site working

### What do you get instead?
error 500, and the console said `PHP Fatal error:  Uncaught ValueError: Path cannot be empty in [no active file]`
![Screenshot_20231023_082912](https://github.com/yii2-extensions/app-basic/assets/10651085/87a8c78a-e3a7-4580-a1bf-819a305fe4ed)

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      |  PHP 8.1.24
| Operating system | Fedora 37

**Comment by terabytesoftw** [comment]
Related https://github.com/yiisoft/yii2/pull/20021

Please update with composer update, it should work now.

**Comment by terabytesoftw** [comment]
![image](https://github.com/yii2-extensions/app-basic/assets/42547589/2e1c4fc8-8f2d-46fe-a53c-6bc0c2098de6)

Work now.

![image](https://github.com/yii2-extensions/app-basic/assets/42547589/1b876658-eb09-4e8e-b29c-46268fd2aea6)

**Comment by biladina** [comment]
okay, it works now, thank you..
