### ISSUE TITLE
installed package from composer disappear after installing package via NPM

### ISSUE THREAD

**Issue by biladina** [yii2-extensions/app-basic#69]
### What steps will reproduce the problem?
- clone this repo
- run `composer install`
- install any NPM package, like tabler, `npm i @tabler/core`

### What is the expected result?
installed package from composer not disappear

### What do you get instead?
installed package from composer disappear

### Additional info
this is after running `composer install`
![Screenshot_20240120_210306](https://github.com/yii2-extensions/app-basic/assets/10651085/fb2ef65d-3340-444f-85e9-72178ed9dc25)

and this is after install NPM package, package that previously installed disappear
![Screenshot_20240120_210333](https://github.com/yii2-extensions/app-basic/assets/10651085/df24a467-f2f4-4869-8e0a-08c8df196759)

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.1
| Operating system | Main OS is Fedora 38, but I run this app from [yii3 docker image](https://github.com/yiisoft/yii-docker) and [httpd docker image](https://hub.docker.com/_/httpd)

**Comment by terabytesoftw** [comment]
If I use that is correct, i will use foxy, i will solve it tomorrow.
